### ISSUE TITLE
stage 1(블록 이미지)

### ISSUE THREAD

**Issue by ChaeJuyoung** [ft-jasong/kmu_capstone#2]
![a](https://user-images.githubusercontent.com/104220181/168153698-1cd06edb-f71b-41b5-b5f9-096d644c55b5.png)
![b](https://user-images.githubusercontent.com/104220181/168153701-a84c0bfc-34eb-4e47-befa-200d1228a096.png)
![c](https://user-images.githubusercontent.com/104220181/168153702-efed5033-569a-4332-a242-b3f759a50a52.png)
![d](https://user-images.githubusercontent.com/104220181/168153704-177cae90-d105-445f-953a-6f3f78b6236b.png)
![e](https://user-images.githubusercontent.com/104220181/168153707-f6050199-4fba-42cc-b3db-504bac0ea3af.png)
![f](https://user-images.githubusercontent.com/104220181/168153708-2874ff8e-b9f0-410e-804a-23bcc44ae15f.png)
![g](https://user-images.githubusercontent.com/104220181/168153711-adfeb81d-e2f8-4b1d-ac89-9935b83848ca.png)
![h](https://user-images.githubusercontent.com/104220181/168153712-75b778ea-8f7c-4ee6-8181-bbc3d8dda339.png)
![i](https://user-images.githubusercontent.com/104220181/168153713-4ef28363-49a9-4147-a184-041860087afa.png)
![j](https://user-images.githubusercontent.com/104220181/168153714-a9f13cf1-0f43-41f7-965b-8fa5a39c7adb.png)
![k](https://user-images.githubusercontent.com/104220181/168153716-68635603-d7ed-4b4e-966a-f9e9c898fca5.png)
![l](https://user-images.githubusercontent.com/104220181/168153720-e3d4d071-45aa-42ee-ae6a-69b47846024a.png)
![m](https://user-images.githubusercontent.com/104220181/168153724-0ae833d0-e7a9-4626-bba9-d103bf81fd8f.png)
![map1](https://user-images.githubusercontent.com/104220181/168153728-74c99b24-e983-490e-8979-378e9f27664d.png)
![n](https://user-images.githubusercontent.com/104220181/168153742-58016ede-5797-45ce-8ca8-45e2654686b0.png)
![o](https://user-images.githubusercontent.com/104220181/168153744-811a34b4-6419-4d3d-b682-ad5864bcd534.png)
![p](https://user-images.githubusercontent.com/104220181/168153749-6adb8ee6-375d-4731-9d59-dfb8d19f9742.png)
![p-removebg-preview](https://user-images.githubusercontent.com/104220181/168153753-5378593d-184e-4d8d-b609-487aacd13519.png)
![q](https://user-images.githubusercontent.com/104220181/168153756-2d13ab5d-de1f-4ebf-8ece-876015e0fbbd.png)

**Comment by ft-jasong** [comment]
block img files
