### ISSUE TITLE
Stage 2(블록 이미지)

### ISSUE THREAD

**Issue by ChaeJuyoung** [ft-jasong/kmu_capstone#3]
![aa](https://user-images.githubusercontent.com/104220181/168154401-6cfeca35-0086-4c28-9660-fab038833e0a.png)
![bb](https://user-images.githubusercontent.com/104220181/168154404-3b5bfed6-c67c-4449-9d49-a31f60d5537d.png)
![cc](https://user-images.githubusercontent.com/104220181/168154406-783f0e61-4815-47df-b00e-f4e7a6464570.png)
![dd](https://user-images.githubusercontent.com/104220181/168154408-e3e5d8c1-38fa-40f1-abe2-79bc523e3b47.png)
![ee](https://user-images.githubusercontent.com/104220181/168154410-b8e14f1d-8b66-4adc-83be-08b459d141a9.png)
![ff](https://user-images.githubusercontent.com/104220181/168154411-efe00f0f-c953-4760-9106-6816d244a432.png)
![gg](https://user-images.githubusercontent.com/104220181/168154414-6dcbe7cb-a858-4d91-9243-3244247c7d6e.png)
![hh](https://user-images.githubusercontent.com/104220181/168154417-7e1c226c-1de0-4182-8d62-2ed5ad1df990.png)
![ii](https://user-images.githubusercontent.com/104220181/168154418-4cbb0be2-9097-4fd8-a4ba-eb51bac136e2.png)
![jj](https://user-images.githubusercontent.com/104220181/168154423-745ce1ad-1721-4b20-8a56-3abb9b4b12eb.png)
![kk](https://user-images.githubusercontent.com/104220181/168154425-5a2ceeb0-3237-4b3a-95db-c5e27cc64803.png)
![ll](https://user-images.githubusercontent.com/104220181/168154429-294a83c1-b348-49ce-9925-47acef26e878.png)
![mm](https://user-images.githubusercontent.com/104220181/168154430-ed04724f-df44-417f-8b2d-611771011aa2.png)
![nn](https://user-images.githubusercontent.com/104220181/168154433-2e8110a2-4cf2-4097-a0ff-59d280abfaf4.png)

**Comment by ft-jasong** [comment]
block img files #2
