### ISSUE TITLE
Stage 3(블록 이미지)

### ISSUE THREAD

**Issue by ChaeJuyoung** [ft-jasong/kmu_capstone#4]
![ddd](https://user-images.githubusercontent.com/104220181/168154740-18c3a888-1fee-4cd1-b261-f7a00c15920e.png)
![eee](https://user-images.githubusercontent.com/104220181/168154745-80b1f13e-8f65-49a8-a3d3-b12464ae72df.png)
![fff](https://user-images.githubusercontent.com/104220181/168154748-d971daee-c798-4c0f-bc16-42fb07b3643e.png)
![ggg](https://user-images.githubusercontent.com/104220181/168154749-52427c3e-6fe4-49fb-bb60-77f6cecb7bea.png)
![hhh](https://user-images.githubusercontent.com/104220181/168154752-677641ba-e667-4a4e-b717-021e07ec95e1.png)
![iii](https://user-images.githubusercontent.com/104220181/168154753-1f3ada09-20c9-40a6-91e3-d4684f1372bc.png)
![jjj](https://user-images.githubusercontent.com/104220181/168154755-5274b21b-8c52-43d3-9570-b177ef2560a1.png)
![kkk](https://user-images.githubusercontent.com/104220181/168154757-d84e4b85-1f7f-4114-a91f-8a4512f6047e.png)
![lll](https://user-images.githubusercontent.com/104220181/168154759-5209780f-8b9d-443d-afa6-be8601c69205.png)
![mmm](https://user-images.githubusercontent.com/104220181/168154761-953d07e0-04ac-4073-8559-a98e65b56a76.png)
![nnn](https://user-images.githubusercontent.com/104220181/168154762-730e8cb5-0af4-485a-b0a3-d88743805d15.png)
![aaa](https://user-images.githubusercontent.com/104220181/168154765-dc235344-ffd6-4c3e-b403-85962b0bdd2f.png)
![bbb](https://user-images.githubusercontent.com/104220181/168154766-7f1b6647-db55-46c7-9b6d-c15ec8836d42.png)
![ccc](https://user-images.githubusercontent.com/104220181/168154768-cb3f9266-a41f-4644-92b6-36b02fba0f1a.png)

**Comment by ft-jasong** [comment]
block img files
